suplock/urls.py
from django.urls import path,include
from django.contrib import admin
from core import views
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view(),name = 'welcome'),
    path('invest_index/',views.invest_index.as_view(),name = 'invest_index'),
    path('invest_option/',views.invest_option.as_view(),name = 'invest_option'),
    path('invest_option/<int:pk>',views.invest_loan.as_view(),name = 'invest_loan'),
    path('invest_wallet/',views.invest_wallet.as_view(),name = 'invest_wallet'),
    path('login_company/' ,views.login_company.as_view(), name='login_company'),
    path('company_index/', views.company_index.as_view(), name = 'company_index'),
    path('logout/', views.logout, name="logout"),
    path('tx_result/', views.tx_result, name="tx_result"),
    path('company_orders/',views.company_order.as_view(), name='company_orders'),
    path('company_orders_rec/',views.company_order_rec.as_view(), name='company_orders_rec'),
    path('add_erc865/', views.hello_world,name='add_erc865'),
    path('getAbiBytecode/', views.getAbiBytecode),
    path('buyERC865/', views.buyERC865),
    path('frontend/return/', views.PaymentReturnView.as_view()),
    path('checkUser/', views.checkUser),
    path('wallet/' ,views.wallet.as_view(), name='wallet'),
    path('company_info/', views.company_info.as_view(), name = 'company_info'),
    path('company_account_pay/', views.company_account_pay.as_view(), name = 'company_account_pay'),
    path('company_account_rec/', views.company_account_rec.as_view(), name = 'company_account_rec'),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('my_notification/', views.my_notification.as_view(),name='my_notification'),
    path('verification_ERP/', views.verification_ERP.as_view(),name='verification_ERP'),
    path('verification_OK/', views.verification_OK.as_view(),name='verification_OK'),
    path('payback/', views.payback_loan.as_view(),name='payback_loan'),
    path('acc_rec_auction',views.acc_rec_auction.as_view(),name='acc_rec_auction'),
    path('acc_rec_auction/<int:pk>',views.buy_acc_rec.as_view(),name='buy_acc_rec'),

]

urlpatterns += static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT
)

core/models.py
from django.db import models
from django.db.models.fields import BooleanField
from django.contrib.auth.models import User
import datetime

from django.urls.base import clear_script_prefix

RATE_CHOICES = (
    (6, '6%'),
    (8, '8%'),
    (10,'10%'),
    (12,'12%'),
)
STATE_CHOICES = (
    (1, '憑證未發出'), ## for orders
    (2, '訂單準備中'),## for orders
    (3, '訂單已完成'),## for orders
    (4, '違約'),  ## for all type
    (5, '未驗證'), ## for verification
    (6, '完成驗證'),## for verification
    (7, '尚未付款'), ## for account payable/receivable
    (8, '發出應付'), ## for account payable/receivable
    (9, '帳款已結清') ## for account payable/receivable
)

LOAN_STATE = (
    (1, '融資中'),
    (2, '融資成功'),
    (3, '融資失敗'),
    (4, '還款結清'),
    (5, '違約')
)
CLASS_CHOICES = (
    (1, '應收'),
    (2, '訂單'),
    (3, '移轉'),
    (4, '貸款'),
    (5, '驗證抵押')
) 
CLASS_CHOICES_2000 = (
    (1, '應收'),
    (2, '訂單'),
    (3, '存貨'),
)
TRANCHE_CHOICES =(
    (1, 'A'),
    (2, 'B'),
    (3, 'C')
)
ARA_CHOICES = (
    (1,'出售中'),
    (2,'成交'),
)
class Invest_user(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) ## user foriegn key
    public_address = models.CharField(max_length=42) ##公鑰
    amount_865 = models.DecimalField(max_digits=12, decimal_places=0, null=True) #核心企業平台幣數量

class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) ## user foriegn key
    uni_num = models.CharField(max_length=100) ##統一編號
    public_address = models.CharField(max_length=42) ##公鑰
    core = models.BooleanField() #是否為核心企業
    amount_a = models.DecimalField(max_digits=12, decimal_places=1, null=True) #核心企業token_A數量
    amount_865 = models.DecimalField(max_digits=12, decimal_places=0, null=True) #核心企業平台幣數量
    create_time = models.DateTimeField(auto_now_add= True) #進入時間
    contract_address = models.CharField(max_length=42,null=True,blank=True) ##合約地址
    company_type = models.CharField(max_length=42,null=True,blank=True) #行業別
    capital = models.DecimalField(max_digits=12, decimal_places=0, null=True) #資本額
    chairman = models.CharField(max_length=42,null=True,blank=True) #董事長
    company_location =  models.CharField(max_length=42,null=True,blank=True) #公司地址
    supervisor = models.CharField(max_length=42,null=True,blank=True) #登記機關
    establish_date = models.CharField(max_length=42,null=True,blank=True) #成立日期
    responsible_person = models.CharField(max_length=42,null=True,blank=True) #負責人
    image = models.ImageField(upload_to='static/image/', blank=True, null=True)  ##logo
    


class Deposit(models.Model):
    deposit_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='deposit_company')
    deposit_amount = models.CharField(max_length=100, null=True, blank=True)  ## 因為使用者可能存超多錢，所已用string存，取用時要先cast成int
    deposit_time = models.DateTimeField(default=datetime.datetime.now) #進入時間
    transactionHash = models.CharField(max_length=66, null=True, blank=True)


class TokenA(models.Model):
    tokenA_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='tokenA_company')
    tokenA_amount = models.CharField(max_length=100, null=True, blank=True)  ## 因為使用者可能存超多錢，所已用string存，取用時要先cast成int
    tokenA_time = models.DateTimeField(default=datetime.datetime.now) #進入時間
    transactionHash = models.CharField(max_length=66, null=True, blank=True)

## temporary for testing 
class Company_orders(models.Model):
    ##设置related_name参数来覆盖名字entry_set以起到相同的作用
    ##範例 c = Company.objects.get(id=1)
    ##    c.send_company.all() returns all order objects related to Company.
    send_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='send_company') ## 一個發出Company 對多 orders
    receive_compamy = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='receive_comapny') ## 一個接收Company 對多 orders
    product  = models.CharField(max_length=40) ##訂單項目
    price = models.IntegerField(null=True, blank=True) ##訂單價格
    start_date = models.DateField(auto_now_add = True ,null=True) ## 發起時間
    end_date = models.DateField() ## 結束時間
    state = models.IntegerField(choices=STATE_CHOICES, default=1) ##狀態
    rate = models.IntegerField(choices=RATE_CHOICES, null=True,  blank=True) ##利息
    transactionHash = models.CharField(max_length=66, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank = True) ##數量 onlyfor 驗證
    class_type = models.IntegerField(choices=CLASS_CHOICES_2000, null=True, blank=True) ##tokenB (應收, 訂單, 移轉, 貸款)



# loan (address _loaner, uint256 _amount, uint16 _class, uint _id, uint256 _interest, uint256 _date)
# bToC (address _from, address _to, uint256 _amount, uint256 _interest, uint _id, uint16 _class, uint16 c_class, uint256 _date)
class TokenB(models.Model):
    amount = models.CharField(max_length=100, null=True, blank=True) ##tokenB金額
    class_type = models.IntegerField(choices=CLASS_CHOICES, null=True, blank=True) ##tokenB (應收, 訂單, 移轉, 貸款)
    token_id = models.CharField(max_length=100, null=True, blank=True) ## tokenB的id, 因為太長所以用charfield
    interest = models.IntegerField(null=True, blank=True)
    date_span = models.IntegerField(null=True, blank=True)
    transfer_count = models.IntegerField(null=True, blank=True) ##移轉次數

    initial_order = models.ForeignKey(Company_orders, on_delete=models.CASCADE, related_name='initial_order', null=True,  blank=True) #指向最一開始的訂單
    pre_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='pre_company', null=True,  blank=True)
    curr_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='curr_company', null=True,  blank=True)
    transactionHash = models.CharField(max_length=66, null=True, blank=True)

    tokenB_balance = models.DecimalField(max_digits=12, decimal_places=0 , default=0, blank=True)##tokenB可使用餘額
    already_transfer = models.DecimalField(max_digits=12, decimal_places=0,  default=0,  blank=True)## 已移轉amount
    already_loan = models.DecimalField(max_digits=12, decimal_places=0 , default=0,   blank=True)## 已借款amount

    pmt = models.IntegerField(null=True, blank=True)

    state = models.IntegerField(choices=LOAN_STATE, null=True, blank=True)

# loancertificate資料表
# mintCertificate (_loan_id, _borrow_company, _principle, _interest, _datespan, _class)
class LoanCertificate(models.Model):
    tokenB  = models.ForeignKey(TokenB,on_delete=models.CASCADE ,related_name='from_tokenB', null=True,  blank=True) ## 來自哪個tokenB 'kevin'
    loan_id = models.CharField(max_length=100, null=True, blank=True) ## tokenB的id, 因為太長所以用charfield
    loan_company = models.ForeignKey(Company,on_delete=models.CASCADE ,related_name='loan_company', null=True,  blank=True) ## 借錢企業
    principle = models.CharField(max_length=100, null=True, blank=True) ## 融資多少錢
    avail_amount = models.CharField(max_length=100, null=True, blank=True) 
    interest = models.IntegerField(null=True, blank=True)
    date_span = models.IntegerField(null=True, blank=True) ## 這裡要紀錄期數（單位為月）
    curr_span = models.IntegerField(null=True, blank=True) ## 剩餘期數
    riskClass = models.IntegerField(choices=TRANCHE_CHOICES, null=True, blank=True)  ## 分券種類
    transactionHash = models.CharField(max_length=66, null=True, blank=True)

# tranche資料表

class Tranche(models.Model):
    # (address _investor, uint _loan_id, uint _class, uint _amount)
    loanCertificate = models.ForeignKey(LoanCertificate,on_delete=models.CASCADE ,related_name='from_certificate', null=True,  blank=True) ##來自哪比loan_certificate 'kevin'
    investor = models.ForeignKey(User,on_delete=models.CASCADE ,related_name='investor', null=True,  blank=True)
    loan_id = models.CharField(max_length=100, null=True, blank=True) ## tokenB的id, 因為太長所以用charfield
    riskClass = models.IntegerField(choices=TRANCHE_CHOICES, null=True, blank=True)  ## 分券種類
    amount = models.CharField(max_length=100, null=True, blank=True) ##tokenB金額
    accu_earning = models.CharField(max_length=100, null=True, default='0') ## 利息累積多少錢
    principle_remain =  models.CharField(max_length=100, null=True, blank=True) ## 剩餘本金（算irr)


# investorDividend 資料表
class LoanPayable(models.Model):
    tokenB = models.ForeignKey(TokenB, on_delete=models.CASCADE ,related_name='loan_id', null=True,  blank=True)
    term_principle = models.TextField(null=True, blank=True)
    term_interest = models.TextField(null=True, blank=True)
    term = models.IntegerField(null=True, blank=True)


class Acc_rec_for_sale(models.Model):
    tokenB = models.ForeignKey(TokenB, on_delete=models.CASCADE ,related_name='acc_recB_id', null=True,  blank=True)
    opening_price = models.IntegerField(null=True, blank=True)
    core_company = models.ForeignKey(Company, on_delete=models.CASCADE ,related_name='core_company', null=True,  blank=True)
    pre_own = models.ForeignKey(Company, on_delete=models.CASCADE ,related_name='pre_own', null=True,  blank=True)
    state =  models.IntegerField(choices=ARA_CHOICES, null=True, blank=True)

class Payback_record(models.Model):
    tokenB = models.ForeignKey(TokenB, on_delete=models.CASCADE ,related_name='payback_loan_id', null=True,  blank=True)
    term = models.IntegerField(null=True, blank=True) ## 還錢的期數
    amount = models.TextField(null=True, blank=True)  ## 還錢的金額


##每期分紅紀錄
class Dividend_record(models.Model):
    uni_tranche = models.ForeignKey(Tranche, on_delete=models.CASCADE ,related_name='dividend_record', null=True,  blank=True)
    term = models.IntegerField(null=True, blank=True) ## 期數
    principle_interest = models.TextField(null=True, blank=True) ##該期本利和

core/forms.py
from django import forms
from django.forms.forms import Form
from .models import Company
from django.contrib.auth.models import User
from .fields import ListTextWidget

RATE_CHOICES = (
    (6, '6%'),
    (8, '8%'),
    (10,'10%'),
    (12,'12%'),
)
SELL_ACC_CHOICES = (
    (95, '95%'),
    (90, '90%'),
    (85, '85%'),
    (80, '80%'),
)

##註冊表單  
class user_register(forms.Form):
    username = forms.CharField()
    uni_num = forms.CharField()
    email = forms.CharField()
    password = forms.CharField()
    _password = forms.CharField()
    address = forms.CharField()
    
##登入表單
class user_login(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

## 課金表單
class deposit(forms.Form):
    amount_a = forms.DecimalField()

## 發訂單表單 (token A to B)
class set_order_rate(forms.Form):
    orders_id = forms.CharField()
    rec_company_name = forms.CharField()
    rec_com_address = forms.CharField()
    rate = forms.ChoiceField(choices = RATE_CHOICES ,widget = forms.Select ,required=True)

## 發應收表單
class send_account_pay(forms.Form):
    orders_id = forms.CharField()
    rec_company_name = forms.CharField()
    rec_com_address = forms.CharField()

## loan表單
#(address _loaner, uint256 _amount, uint16 _class, uint _id, uint256 _interest, uint256 _date)
class set_loan(forms.Form):
    optype = forms.CharField() # use operation type to decide which view to pass this form 
    orders_interest = forms.CharField()
    loan_TOKENB_id = forms.CharField(required=True)
    orders_id = forms.CharField()
    orders_from_company_name = forms.CharField()
    orders_price = forms.CharField()
    rate = forms.ChoiceField(choices = RATE_CHOICES ,widget = forms.Select) ##only for 應收移轉

# 移轉表單
class companyListForm(forms.Form):
    optype = forms.CharField(required=True)
    bToC_TOKENB_id = forms.CharField(required=True)
    bToC_interest = forms.CharField(required=True)
    bToC_id = forms.CharField(required=True)
    bToC_from_company_name = forms.CharField(required=True)
    bToC_to_company_name = forms.CharField(required=True)
    bToC_price = forms.CharField(required=True)
    rate = forms.ChoiceField(choices = RATE_CHOICES ,widget = forms.Select) ##only for 應收移轉

    def __init__(self, *args, **kwargs):
        _company_list = kwargs.pop('data_list', None)
        super(companyListForm, self).__init__(*args, **kwargs)
        # the "name" parameter will allow you to use the same widget more than once in the same
        # form, not setting this parameter differently will cuse all inputs display the
        # same list.
        self.fields['bToC_to_company_name'].widget = ListTextWidget(data_list=_company_list, name='bToC_to_company_name')

## 應收移轉
class acc_rec_form(forms.Form):
    optype = forms.CharField(required=True)
    bToC_TOKENB_id = forms.CharField(required=True)
    bToC_interest = forms.CharField(required=True)
    bToC_id = forms.CharField(required=True)
    bToC_from_company_name = forms.CharField(required=True)
    bToC_price = forms.CharField(required=True)
    actual_price = forms.CharField(required=True)
    rate = forms.ChoiceField(choices = SELL_ACC_CHOICES ,widget = forms.Select) ##only for 應收移轉


# (address _investor, uint _loan_id, uint _class, uint _amount)
class buyTranche(forms.Form):
    _loan_id = forms.CharField()
    _amount = forms.CharField()
    _class = forms.CharField() ##only for 應收移轉

class paybackForm(forms.Form):
    _loan_id = forms.CharField()
    _amount = forms.CharField()

class buy_acc_rec(forms.Form):
    arc_rec_id = forms.IntegerField
    _amount = forms.CharField()

core/templates/acc_rec_auction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>投資標的</title>
    {% load static %}
    {% include 'nav_login.html' %} 
    <link rel="stylesheet" href="{%static 'css/acc_rec_auction.css' %}">
</head>
<body>
    <div class="page_title"><h2 style="font-size: 36px;">應收帳款買賣</h2></div>
    <main class="main_content">
        <div class="inv_option">
            <div class="whole_table">
            <table class="table" id="loan_table">
                <thead>
                    <tr>
                        <th>應收編號</th>
                        <th>擔保公司</th>
                        <th>應收金額</th>
                        <th>開價</th> 
                        <th>購買</th>
                    </tr>
                </thead>
                <tbody>
                    {% for option in acc_rec %}
                    <tr name='make_id' class="tr_height">
                        <td >ARS-{{option.id}}</td>
                        <td >{{option.core_company.user}}</td>
                        <td >{{option.tokenB.amount}}</td>
                        <td>{{option.opening_price}}</td>
                        {% if option.state == 1 %}
                        <td><a  href="{% url 'buy_acc_rec' pk=option.id %}" ><button id="-{{forloop.counter}}" class="show detail_btn">購買</button></a></td>
                        {% else %}
                        <td>已成交</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
            <div class='paginator'>
                {% if page_obj.has_previous %}
                <a  href="?page={{ page_obj.previous_page_number }}">上一頁</a>
                &emsp;
                {% endif %}
                {% if page_obj.has_next %}
                <a  href="?page={{ page_obj.next_page_number }}">下一頁</a>
                {% endif %}
            </div>
            {% endif %}
            </div>
        </div>

    </main>

<script>
    
</script>

</body>
</html>

core/templates/company_account_pay.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>我的訂單</title>
    {% include 'nav_login.html' %}
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/company_orders.css' %}">
</head>
<body>
<div class="loader-wrapper" id = 'waiting'>
    <div>
    <span class="loader"><span class="loader-inner"></span></span>
    </div>
    <h2 style="color: white; margin-top: 20px;">Wait for the transaction complete</h2>
</div>
<main class="main_content" id = 'fade_out'>
    <div class='content_title'> 
        <h2>應收/應付管理</h2>
    </div>
    <!-- 點擊變暗 -->
    <div id = 'overlay'></div> 
    <!-- 彈出小卡 -->
    <div id = 'pop_div' class = "add_rate">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="add_title">
                <h2 class="title_text">設定接收廠商可借貸利率</h2>
            </div>
            <input type="text" style="display: none;" name="orders_id" id="orders_id">
            <div class="money_input">
                <h2 class="title_text">訂單編號：</h2>
                <input type="text" class = "rec_comp" readonly='readonly' id = 'modify_id' value=''>
            </div>
            <div class="money_input">
                <h2 class="title_text">廠商名稱：</h2>
                <input type="text" class = "rec_comp" readonly='readonly' id = 'rec_company_name'name = 'rec_company_name' value=''>
            </div>
            <div class="money_input">
                <h2 class="title_text">廠商地址：</h2>
                <input type="text" class = "address_" readonly='readonly' id = 'addr' name = 'rec_com_address' value=''>
            </div>
            <div class='add_money_btn'>
                <button class="submit_btn" type="button" id='send' name="confirm">發出應收</button>
            </div>
        </form>
    </div>
    <div class="outer">
    <!-- <input class='btn_div'  id = 'btn_1' value = '透過憑證發出訂單'></input> -->
        <div class="table_above_tag">
            <div class='send_btn' id='clicked_1'>
                <h2 class="send_order" >應付</h2>
            </div>
            <a class='recieve_btn' id= 'clicked_2' href="{% url 'company_account_rec' %}">
                <h2 class="send_order" >應收</h2>
            </a>
        </div>
        <div class="ordersTable" id="sendOrder">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="display: none;">訂單編號</th>
                        <th>接收公司</th>
                        <th>項目</th>
                        <th>金額</th>
                        <th>開始時間</th>
                        <th>結束時間</th>
                        <th>狀態</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr name = 'make_id' onclick="{% if order.state == 7 %}  pop_set_rate() {% endif %}" >
                        <td name = 'percent' style="display: none;">{{ order.get_rate_display }}</td>
                        <td name = 'order_id' style="display: none;">{{order.id}}</td>
                        <td name= 'to_id' >{{order.receive_compamy.user}}</td>
                        <td >{{order.product}}</td>
                        <td>{{order.price}}</td>
                        <td>{{order.start_date|date:'Y-m-d'}}</td>
                        <td>{{order.end_date|date:'Y-m-d'}}</td>
                        <td name = 'state' class="{% if order.state == 8 %}greenText{% endif %}">{{ order.get_state_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
            <div class='paginator'>
                {% if page_obj.has_previous %}
                <a  href="?page={{ page_obj.previous_page_number }}">上一頁</a>
                &emsp;
                {% endif %}
                {% if page_obj.has_next %}
                <a  href="?page={{ page_obj.next_page_number }}">下一頁</a>
                {% endif %}
            </div>
            {% endif %}
        
        </div>
    </div>
  
</main>

</body>
<script type="text/javascript" src="{%static 'js/check_user.js' %}"></script>

<script>
    let optionArray = [];
    let reciverArray = [];
    let orderIDArray = [];
    let stateArray = [];
    const waiting = document.getElementById('waiting'); //等待
    const fade = document.getElementById('fade_out'); //等待
    const overlay = document.getElementById('overlay');
    const pop_div = document.getElementById('pop_div');
    const addr = document.getElementById('addr');
    const orders_id = document.getElementById('orders_id');
    const state = document.getElementsByName('state');
    const to_id = document.getElementsByName('to_id');
    const make_id = document.getElementsByName('make_id');
    const order_id = document.getElementsByName('order_id');
    const rec_company_name = document.getElementById('rec_company_name');
    const company_addr_dict =  {{ company_addr_dict|safe }};   //django -> js (ignore the warning)
    function pop_set_rate(){
        pop_div.classList.add('active');
        overlay.classList.add('active');
    }
    overlay.addEventListener('click',()=>{
        pop_div.classList.remove('active');
        overlay.classList.remove('active');
    });
    for (let i = 0; i < to_id.length; i++){
        // set unique id for every order
        to_id[i].setAttribute("id","receiver-"+i); 
        make_id[i].setAttribute('id','option-'+i);
        order_id[i].setAttribute('id','orderID-'+i);
        state[i].setAttribute('id','state-'+i);
        optionArray[i] = document.getElementById('option-'+i);
        reciverArray[i] = document.getElementById('receiver-'+i);
        orderIDArray[i] = document.getElementById('orderID-'+i);
        stateArray[i] =  document.getElementById('state-'+i);
        // 客製化每個訂單彈出的小卡
        optionArray[i].addEventListener('click',()=>{
            for (let ele in company_addr_dict){
                if (reciverArray[i].innerHTML == ele){
                    addr.value = company_addr_dict[ele];
                    rec_company_name.value = reciverArray[i].innerHTML;
                    orders_id.value = orderIDArray[i].innerHTML;
                    $('#modify_id').val('AR-'+orderIDArray[i].innerHTML)
                };
            };
        });
    };
    //只有憑證未發出才會彈出小卡
    for (let ele in state){
        if (state[ele].innerHTML == '訂單準備中'){
            state[ele].style.color = 'green'
        }
        else if (state[ele].innerHTML == '訂單已完成'){
            state[ele].style.color = 'blue'
        }
        else if (state[ele].innerHTML == '違約'){
            state[ele].style.color = 'red'
        }
        
    }
    $(document).ready(async function () {
        $('#send').on('click',async  function (e) {
            var curr_accounts = await ethereum.request({ method: 'eth_requestAccounts' });
            e.preventDefault();
            var form = $(this).parents('form:first');
            let check_addr = await checkUser(form.serializeArray(), curr_accounts[0]);
            $.ajax({
                method: "POST",
                url: "/checkUser/",
                data: { 'check_addr': check_addr },
                dataType: "json"
            }).done(async function (res) {
                if (res['check'] == 'passed') {
                    form.submit();
                    $('#waiting').css("display", "flex");
                    $('#fade').css("display", "none");
                    $('#pop_div').css("display", "none");
                } else {
                    alert('wrong account');
                }
            });
        });

    });

</script>

</html>

core/templates/my_notification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>通知</title>
    {% include 'nav_login.html' %}
    {% load static %}
    <link rel="stylesheet" href="{%static 'css/my_notification.css' %}">
</head>
<body>
    <main class="main_content" id = "fade_out">
        {% include 'company_index_left.html' %}
        <div class="notify_table">
            <h2 class="table_title">訊息通知</h2>
            <div class="notify_content">
                {%for notify in request.user.notifications.all|slice:":9" %}
                <div class="notify_tr {% if not  notify.unread %}read_gray{% endif %}" value ="{{notify.id}}"id = "notify-{{ forloop.counter}}">
                    <div class="inner_text {% if not notify.unread %}read{% endif %}" id ="inner-{{ forloop.counter}}" >
                        <h2 class="notify_title">{{ notify.actor }}向您{{ notify.verb }}</h2>
                        <h3 class="notify_time">{{notify.timesince}}之前</h3>
                    </div>
                </div>
                {% empty %}
                <div class="clear">暫無消息.....</div>
                {% endfor %}
            </div>
            
        </div>
    </main>
</body>
<script>
    for (let i = 1; i<10 ; i++){
        $('#notify-'+i).click(function () {
            $('#notify-'+i).addClass('read_gray')
            $('#inner-'+i).addClass('read')
        event.preventDefault();
        $.ajax({
            url: '/my_notification/',
            type: 'post',
            data: {
                notify_ID: $('#notify-'+i).attr('value')
            },
        })
    })
}
</script>
</html>

core/templates/payment_success.html
<!DOCTYPE html>

<html>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        #p {
            display: none;
        }
    </style>
</head>

<body>
    <h1>成功買幣</h1>
    <p id="p">{{ res }} </p>
    <p>{{ receipt }}</p>
    <p>{{event}}</p>
    <input id="back_btn" type="submit" value="回首頁">

    <script type="text/javascript">
        $(document).ready(function () {
            $('#back_btn').on("click", ()=>{
                location.href = 'http://127.0.0.1:8000/';
            })
        });
    </script>
</body>

</html>